config/routes.rb
Rails.application.routes.draw do
  get 'users/largest_bookshelf' => 'users#largest_bookshelf'

  get 'favorite/:id' => 'userbooks#favorite'
  post 'favorite/:id' => 'userbooks#favorite'

  root 'sessions#new'

  get '/auth/google_oauth2/callback' => 'sessions#create'

  get '/signin' => 'users#new', :as => :signin
  post '/signin' => 'users#create'
  delete '/signout' => 'users#destroy', :as => :signout

  get '/login' => 'sessions#new'
  # get '/sessions/new', to: 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :sessions
    # get rid of routes im not using
  resources :users
  resources :userbooks
  resources :books
  resources :authors do
    resources :books, only: [:show, :index, :new, :edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  has_many :users, through: :books
  accepts_nested_attributes_for :books

  validates :name, presence: true, uniqueness: true

  def book_ids=(ids)
    ids.each do |id|
      book = Book.find(id)
      self.books << book
    end
  end

    #find the most common genre from the author's books and return it
    #ties decided by newest? or oldest?
  def most_popular_genre
    # account for case where an author is made with no books associated
    return "genre"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books
  has_many :users, :through => :user_books
  belongs_to :author

  validates :title, presence: true, uniqueness: true
  validates :genre, presence: true
  validates :pages, presence: true
  validates :author_id, presence: true

  enum genre: [ :Action, :Adventure, :Art, :Autobiography, :Anthology, :Biography, :Book_Review, :Chick_Lit, :Children, :Cookbook, :Comic_Book, :Coming_of_age, :Crime, :Diary, :Dictionary, :Drama, :Encyclopedia, :Fairytale, :Fantasy, :Fiction, :Guide, :Graphic_Novel, :Health, :History,
    :Horror, :Journal, :Math, :Memoir, :Mystery, :New_Age, :Non_Fiction, :Prayer, :Paranormal, :Religious, :Picture_Book, :Poetry, :Political, :Review, :Romance, :Satire, :Science, :Self_Help, :Short_Story, :Suspense, :Textbook, :Thriller, :Travel, :Young_Adult ]

  def author_name=(name)
    self.author = Author.find_or_create_by(name: name)
  end

  def author_name
    self.author ? self.author.name : nil
  end

  def author_attributes=(author)
    self.author = Artist.find_or_create_by(name: author.name)
    self.author.update(author)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_books
  has_many :books, :through => :user_books
  has_many :authors, through: :books
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  #returns the User with the biggest bookshelf
  def self.largest_bookshelf
    User.left_joins(:books).group(:id).order('count(books.id) desc').limit(1).first
  end
end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.valid?
      @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    Author.find(params[:id]).destroy
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/concerns/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:author_id]
      @books= Author.find(params[:author_id]).books
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    if params[:author_id] && !Author.exists?(params[:author_id])
      redirect_to authors_path, alert: "Author not found."
    else
      @book = Book.new(author_id: params[:author_id])
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      if !session[:user_id].nil?
        User.find(session[:user_id]).books << @book
      end
      redirect_to book_path(@book)
      # redirect_to new_book_path()  brand new http request
    else
      render :new
    end
  end

  def edit
    if params[:author_id]
      author = Author.find_by(id: params[:author_id])
      if author.nil?
        redirect_to authors_path, alert: "Author not found."
      else
        @book = author.books.find_by(id: params[:id])
        redirect_to author_books_path(author), alert: "Book not found." if @book.nil?
      end
    else
      @book = Book.find(params[:id])
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :genre, :pages, :author_name, :author_id)
  end
end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if auth && auth[:provider] == "google_oauth2"
      @user = User.find_or_create_by(email: auth[:info][:email]) do |u|
        u.name = auth[:info][:first_name]
        u.email = auth[:info][:email]
        u.password = SecureRandom.hex
      end
      session[:user_id] = @user.id
      redirect_to @user
    else
      @user = User.find_by(email: params[:email])
      # If @user exist and the password is good
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to @user
      else
        redirect_to '/'
      end
    end
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/concerns/userbooks_controller.rb
class UserbooksController < ApplicationController
  def favorite
    @user_book = UserBook.find(params[:id])

    # @user_book switch from false to true or true to false
    if @user_book.favorite == false
      @user_book.favorite = true
    else
      @user_book.favorite = false
    end
    @user_book.save

    @user = User.find(@user_book.user_id)
    redirect_to @user
  end

  private

  def userbook_params
    params.require(:userbook).permit(:favorite)
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    if session.include? :user_id
      @user = User.find(params[:id])
    else
      redirect_to '/'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    @user.book_ids = params[:user][:book_ids]

    @user.update(user_params)

    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def largest_bookshelf
    @user = User.largest_bookshelf
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User deleted."
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :book_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_authorform.html.erb
<%= form_for @author do |f| %>
  Name: <%= f.text_field :name %><br>
  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing "<%= @author.name %>"</h1>

<%= render partial: "authorform", locals: {author: @author} %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<p><%= link_to "New Author", new_author_path%></p>

<tbody>
  <% @authors.all.each do |author| %>
    <tr>
       <td>Name: <%= link_to author.name, author_path(author) %></td><br>
       <td>Book Total: <%= author.books.count %></td><br><br>
    </tr>
  <% end %>
</tbody>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render partial: "authorform", locals: {author: @author} %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<tbody>
  <tr>
    <td>Name: <%= @author.name %></td>
  </tr>
</tbody>

<%= link_to "New Book", new_author_book_path(@author) %>

<h3><%= pluralize(@author.books.count, 'Book') %></h3>
<ul>
  <% @author.books.each do |b| %>
    <li><%= link_to b.title, author_book_path(b) %></li>
  <% end %>
</ul>

<p><%= link_to "Edit Author", edit_author_path(@author)%></p>

app/views/books/_bookform.html.erb
<%= form_for @book do |f| %>
  Title: <%= f.text_field :title %><br>
  Genre: <%= f.select :genre, Book.genres.keys.to_a %><br>
  Pages: <%= f.text_field :pages %><br>
  Author: <%= f.text_field :author_name, list: "authors_autocomplete" %><br>
  <datalist id="authors_autocomplete">
    <% Author.all.each do |author| %>
      <option value="<%= author.name %>">
    <% end %>
  </datalist>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing "<%= @book.title %>"</h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(@book.errors.count, "error") %>
      prohibited this post from being saved:
    </h3>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render partial: "bookform", locals: {book: @book} %>

app/views/books/index.html.erb
<h1>Books</h1>

<p><%= link_to "New Book", new_book_path%></p>

<tbody>
  <% @books.all.each do |book| %>
    <tr>
      <td>Title: <%= link_to book.title, book_path(book) %></td><br>
      <td>Genre: <%= book.genre %></td><br>
      <td>Pages: <%= book.pages %></td><br>
      <td>Author: <%= link_to book.author.name, author_path(book.author) if book.author%></td><br><br>
    </tr>
  <% end %>
</tbody>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render partial: "bookform", locals: {book: @book} %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<tbody>
  <tr>
    <td>Title: <%= @book.title %></td>
    <td>Genre: <%= @book.genre %></td>
    <td>Pages: <%= @book.pages %></td>
    <td>Author: <%= link_to @book.author.name, author_path(@book.author) if @book.author%></td>
  </tr>
</tbody>

<p><%= link_to "Edit Book", edit_author_book_path(@book.author, @book) if @book.author %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookShelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- script taken from facebook tutorial -->
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : 1909421102688170,
          cookie     : true,
          xfbml      : true,
          version    : 'v3.2'
        });

        FB.AppEvents.logPageView();

      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "https://connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    <h2>Navbar</h2>
    <p>
      <%= link_to "Users", users_path %>
      <%= link_to "Authors", authors_path %>
      <%= link_to "Books", books_path %>
    </p>

    <% if session.include? :user_id %>
      <p> Welcome <%= User.find(session[:user_id]).name %> <%= link_to "log out", logout_path, method: :delete %> </p>
    <% else %>
      <p> <%= link_to "log in", login_path %> Are you new? <%= link_to "sign up", signin_path %> </p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing "<%= @user.name %>"</h1>

<%= form_for @user do |f| %>
  Name: <%= f.text_field :name %><br>

  <div class="field">
    <%= f.label "Add/Remove Books from Shelf" %><br>
    <%= f.collection_check_boxes :book_ids, Book.all, :id, :title do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<% if @users.present? %>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>Name: <%= link_to user.name, user_path(user) %></td><br>
        <td>Email: <%= user.email %></td><br><br>
      </tr>
    <% end %>
  </tbody>
<%end%>

app/views/users/largest_bookshelf.html.erb
<p><%= User.largest_bookshelf.name %> has the largest bookshelf</p>

app/views/users/new.html.erb
<h1>Create a User</h1>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br />

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br />

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%=@user.name%>'s Bookshelf</h1>

<% if params.has_key?(:message) %>
  <p><%= params[:message] %></p>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Genre</th>
    <th>Favoite</th>
  </tr>
<% @user.user_books.each do |userbook| %>
  <tr>
    <td><%= link_to userbook.book.title, book_path(userbook.book) %></td>
    <td><%= userbook.book.genre %></td>
    <td><a href="/favorite/<%= userbook.id%>"><%= userbook.favorite %></a></td>
  </tr>
<% end %>
</table><br>

<%= link_to "Edit User/Add books to shelf", edit_user_path(@user) %><br>

<%= link_to "Who has the largest Bookshelf", 'largest_bookshelf' %>